// Copyright 2026 Marc-Antoine Ruel. All rights reserved.
// Use of this source code is governed under the Apache License, Version 2.0
// that can be found in the LICENSE file.

// WebSocket support for the OpenAI Responses API.
//
// See https://developers.openai.com/api/docs/guides/websocket-mode

package openairesponses

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"iter"
	"net/http"
	"strings"
	"sync"

	"github.com/maruel/genai"
	"github.com/maruel/genai/base"
	"github.com/maruel/genai/internal"
	"github.com/maruel/genai/scoreboard"
	"github.com/maruel/roundtrippers"
	"golang.org/x/net/websocket"
)

// wsConn abstracts a WebSocket text-message connection for recording/replay.
type wsConn interface {
	Send(data string) error
	Receive(msg *string) error
	Close() error
}

// websocketConn adapts *websocket.Conn to wsConn.
type websocketConn struct {
	*websocket.Conn
}

func (c *websocketConn) Send(data string) error {
	return websocket.Message.Send(c.Conn, data)
}

func (c *websocketConn) Receive(msg *string) error {
	return websocket.Message.Receive(c.Conn, msg)
}

// WebSocketConn is a persistent WebSocket connection to the OpenAI Responses API.
//
// It implements genai.Provider and io.Closer. Each GenSync/GenStream call sends a
// response.create message and collects the streaming response. Responses are
// automatically chained via previous_response_id for lower latency on multi-turn
// tool-call loops.
//
// The connection tracks previously sent messages via Reply.Opaque metadata.
// On subsequent calls, only new messages (the delta) are sent to the server,
// since it already has the prior conversation via previous_response_id.
//
// Key constraints:
//   - One response in-flight at a time (no multiplexing)
//   - 60-minute connection limit
//   - Compatible with store=false and ZDR
//
// Create via Client.WebSocket().
//
// https://developers.openai.com/api/docs/guides/websocket-mode
type WebSocketConn struct {
	base.NotImplemented

	client *Client

	mu sync.Mutex
	// Protected by mu.
	ws wsConn
}

// WebSocket opens a persistent WebSocket connection to the OpenAI Responses API.
//
// The returned connection inherits the client's model, API key, and base URL.
// Call Close() when done.
func (c *Client) WebSocket(ctx context.Context) (*WebSocketConn, error) {
	if c.impl.Model == "" {
		return nil, errors.New("a model is required")
	}
	// Derive WebSocket URL from the client's base URL.
	wsURL := strings.Replace(c.baseURL, "https://", "wss://", 1)
	wsURL = strings.Replace(wsURL, "http://", "ws://", 1)
	wsURL += "/responses"

	wsCfg, err := websocket.NewConfig(wsURL, wsURL)
	if err != nil {
		return nil, fmt.Errorf("failed to create websocket config: %w", err)
	}
	// Extract auth headers from the HTTP client's transport chain.
	wsCfg.Header = http.Header{}
	wsCfg.Header.Set("OpenAI-Beta", "responses=v1")
	if h, ok := c.impl.ProviderBase.Client.Transport.(*roundtrippers.Header); ok {
		for k, vs := range h.Header {
			for _, v := range vs {
				wsCfg.Header.Set(k, v)
			}
		}
	}
	raw, err := wsCfg.DialContext(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to connect to websocket %s: %w", wsURL, err)
	}
	return &WebSocketConn{
		client: c,
		ws:     &websocketConn{raw},
	}, nil
}

// Name implements genai.Provider.
func (w *WebSocketConn) Name() string {
	return w.client.Name()
}

// ModelID implements genai.Provider.
func (w *WebSocketConn) ModelID() string {
	return w.client.ModelID()
}

// OutputModalities implements genai.Provider.
func (w *WebSocketConn) OutputModalities() genai.Modalities {
	return w.client.OutputModalities()
}

// Capabilities implements genai.Provider.
func (w *WebSocketConn) Capabilities() genai.ProviderCapabilities {
	return genai.ProviderCapabilities{}
}

// Scoreboard implements genai.Provider.
func (w *WebSocketConn) Scoreboard() scoreboard.Score {
	return w.client.Scoreboard()
}

// HTTPClient implements genai.Provider.
//
// Returns the underlying HTTP client for fetching results (e.g. videos) generated by the provider.
func (w *WebSocketConn) HTTPClient() *http.Client {
	return w.client.HTTPClient()
}

// ListModels implements genai.Provider.
//
// Delegates to the underlying HTTP client.
func (w *WebSocketConn) ListModels(ctx context.Context) ([]genai.Model, error) {
	return w.client.ListModels(ctx)
}

// Close implements io.Closer. It closes the WebSocket connection.
func (w *WebSocketConn) Close() error {
	w.mu.Lock()
	defer w.mu.Unlock()
	if w.ws == nil {
		return nil
	}
	err := w.ws.Close()
	w.ws = nil
	return err
}

// newWebSocketConn creates a WebSocketConn with a pre-existing wsConn.
//
// This is used by tests to inject a recorded or replayed connection.
func newWebSocketConn(c *Client, conn wsConn) *WebSocketConn {
	return &WebSocketConn{client: c, ws: conn}
}

// send sends a message over the WebSocket.
func (w *WebSocketConn) send(data []byte) error {
	w.mu.Lock()
	ws := w.ws
	w.mu.Unlock()
	if ws == nil {
		return errors.New("websocket connection is closed")
	}
	return ws.Send(string(data))
}

// recvEvents returns an iterator of streaming events from the WebSocket.
//
// The iterator runs a goroutine that reads messages from the WebSocket.
// The caller must fully consume or discard the iterator to ensure the goroutine exits.
func (w *WebSocketConn) recvEvents(ctx context.Context) (iter.Seq[ResponseStreamChunkResponse], func() error) {
	out := make(chan ResponseStreamChunkResponse, 16)
	errCh := make(chan error, 1)
	ctx, cancel := context.WithCancel(ctx)

	go func() {
		defer close(out)
		defer cancel()
		for {
			w.mu.Lock()
			ws := w.ws
			w.mu.Unlock()
			if ws == nil {
				errCh <- errors.New("websocket connection is closed")
				return
			}
			var msg string
			if err := ws.Receive(&msg); err != nil {
				if errors.Is(err, io.EOF) || strings.Contains(err.Error(), "use of closed network connection") {
					errCh <- nil
				} else {
					errCh <- fmt.Errorf("websocket receive: %w", err)
				}
				return
			}
			var chunk ResponseStreamChunkResponse
			d := json.NewDecoder(strings.NewReader(msg))
			d.DisallowUnknownFields()
			if err := d.Decode(&chunk); err != nil {
				errCh <- fmt.Errorf("failed to decode event: %w; raw: %s", err, msg)
				return
			}
			select {
			case out <- chunk:
			case <-ctx.Done():
				errCh <- ctx.Err()
				return
			}
		}
	}()

	return func(yield func(ResponseStreamChunkResponse) bool) {
			defer cancel()
			for pkt := range out {
				if !yield(pkt) {
					break
				}
			}
			// Drain remaining events to let the goroutine exit.
			for range out {
			}
		}, func() error {
			return <-errCh
		}
}

// buildRequest creates a WSRequest from messages and options.
//
// If the messages contain WebSocket metadata from a prior call (via Reply.Opaque),
// only new messages (the delta) are sent. The server already has prior messages
// via previous_response_id.
func (w *WebSocketConn) buildRequest(msgs genai.Messages, opts ...genai.GenOption) (WSRequest, error) {
	model := w.client.ModelID()
	sentMsgs, prevRespID := findPrevMeta(msgs)
	cleaned := deltaMessages(msgs, sentMsgs)
	req := Response{}
	if err := req.Init(cleaned, model, opts...); err != nil {
		return WSRequest{}, err
	}
	if prevRespID != "" {
		req.PreviousResponseID = prevRespID
	}
	// User override takes precedence.
	for _, opt := range opts {
		if t, ok := opt.(*GenOptionText); ok && t.PreviousResponseID != "" {
			req.PreviousResponseID = t.PreviousResponseID
			break
		}
	}
	return WSRequest{
		Type:     "response.create",
		Response: req,
	}, nil
}

// sendRequest builds and sends a WSRequest.
func (w *WebSocketConn) sendRequest(msgs genai.Messages, opts ...genai.GenOption) error {
	req, err := w.buildRequest(msgs, opts...)
	if err != nil {
		return err
	}
	data, err := json.Marshal(&req)
	if err != nil {
		return fmt.Errorf("failed to marshal request: %w", err)
	}
	return w.send(data)
}

// GenSync implements genai.Provider.
//
// WebSocket mode is always streaming; GenSync collects all fragments and returns
// the accumulated result.
func (w *WebSocketConn) GenSync(ctx context.Context, msgs genai.Messages, opts ...genai.GenOption) (genai.Result, error) {
	fragments, finish := w.GenStream(ctx, msgs, opts...)
	for range fragments {
	}
	return finish()
}

// GenStream implements genai.Provider.
func (w *WebSocketConn) GenStream(ctx context.Context, msgs genai.Messages, opts ...genai.GenOption) (iter.Seq[genai.Reply], func() (genai.Result, error)) {
	res := genai.Result{}
	var finalErr error
	var respID string
	msgCount := len(msgs)

	fnFragments := func(yield func(genai.Reply) bool) {
		if err := w.sendRequest(msgs, opts...); err != nil {
			finalErr = err
			return
		}
		chunks, finish := w.recvEvents(ctx)
		filtered := streamWithRespID(chunks, &respID)
		fragments, finish2 := ProcessStream(filtered)
		sent := false
		for f := range fragments {
			if f.IsZero() {
				continue
			}
			if err := f.Validate(); err != nil {
				finalErr = &internal.BadError{Err: err}
				break
			}
			if err := res.Accumulate(&f); err != nil {
				finalErr = &internal.BadError{Err: err}
				break
			}
			sent = true
			if !yield(f) {
				break
			}
		}
		if err := finish(); finalErr == nil {
			finalErr = err
		}
		usage, _, err := finish2()
		res.Usage = usage
		if finalErr == nil {
			finalErr = err
		}
		if !sent && finalErr == nil {
			finalErr = errors.New("model sent no reply")
		}
	}
	fnFinish := func() (genai.Result, error) {
		if finalErr != nil {
			return res, finalErr
		}
		if err := res.Validate(); err != nil {
			return res, &internal.BadError{Err: err}
		}
		// Emit Opaque metadata so the next call can send only the delta.
		if respID != "" {
			res.Replies = append(res.Replies, emitMeta(respID, msgCount))
		}
		return res, nil
	}
	return fnFragments, fnFinish
}

// GenStreamRaw sends a raw request over the WebSocket and returns the streaming events.
//
// This gives direct access to the WebSocket protocol for power users.
func (w *WebSocketConn) GenStreamRaw(ctx context.Context, in *Response) (iter.Seq[ResponseStreamChunkResponse], func() error) {
	if in.PreviousResponseID == "" {
		// Try to find metadata from prior calls in the context.
		// For raw access, the caller manages previous_response_id manually.
	}
	req := WSRequest{
		Type:     "response.create",
		Response: *in,
	}
	data, err := json.Marshal(req)
	if err != nil {
		return func(yield func(ResponseStreamChunkResponse) bool) {}, func() error {
			return fmt.Errorf("failed to marshal request: %w", err)
		}
	}
	if err := w.send(data); err != nil {
		return func(yield func(ResponseStreamChunkResponse) bool) {}, func() error { return err }
	}
	return w.recvEvents(ctx)
}

// GenSyncRaw sends a raw request over the WebSocket and returns the raw response.
//
// It wraps GenStreamRaw, collecting all streaming events into a single response.
func (w *WebSocketConn) GenSyncRaw(ctx context.Context, in *Response) (*Response, error) {
	chunks, finish := w.GenStreamRaw(ctx, in)
	var lastResp *Response
	for pkt := range chunks {
		if pkt.Type == ResponseCompleted || pkt.Type == ResponseFailed || pkt.Type == ResponseIncomplete {
			r := pkt.Response
			lastResp = &r
		}
	}
	if err := finish(); err != nil {
		return nil, err
	}
	if lastResp == nil {
		return nil, errors.New("no terminal response event received")
	}
	return lastResp, nil
}

var (
	_ genai.Provider = &WebSocketConn{}
	_ io.Closer      = &WebSocketConn{}
)
