// Analyze a picture. The response is streamed out the console as the reply
// is generated.
//
// This requires llamacpp to be running.

package main

import (
	"context"
	"log"
	"os"

	"github.com/maruel/genai"
	"github.com/maruel/genai/providers/llamacpp"
)

func main() {
	ctx := context.Background()
	// Options (as of 2025-08) are:
	// - Gemma-3 and medgemma
	// - Qwen2.5-VL
	// - Mistral-Small-3.2 and Pixtral
	c, err := llamacpp.New(ctx, genai.ModelGood)
	if err != nil {
		log.Fatal(err)
	}
	// Reuse the image generated by example txt_to_img.
	f, err := os.Open("content.jpg")
	if err != nil {
		log.Fatal(err)
	}
	defer func() { _ = f.Close() }()
	msgs := genai.Messages{
		genai.Message{Requests: []genai.Request{
			{Text: "Extensively describe this image."},
			{Doc: genai.Doc{Src: f}},
		}},
	}
	fragments, finish := c.GenStream(ctx, msgs)
	for f := range fragments {
		if _, err = os.Stdout.WriteString(f.Text); err != nil {
			break
		}
	}
	_, _ = os.Stdout.WriteString("\n")
	if _, err = finish(); err != nil {
		log.Fatal(err)
	}
}
