name: Weekly Model Regeneration

on:
  schedule:
    # Run every Sunday at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  regenerate-models:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run model regeneration script
        run: |
          chmod +x ./regen_models.sh
          ./regen_models.sh
      - name: Check for changes
        id: git-check
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
          fi
      - name: Commit and push changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add MODELS.md
          git commit -m "ci: update model list on $(date +'%Y-%m-%d')"
          git push origin HEAD:main
